# Generated by Django 4.2.1 on 2023-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='olusturulma_tarihi',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
