# Generated by Django 4.2.1 on 2023-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hesap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='sifre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
